// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGqzRWmT4KxF0FcMPGhyIIYoZalfNym0U',
    appId: '1:661051223756:web:b6f7f3f983f78f74825c69',
    messagingSenderId: '661051223756',
    projectId: 'rahatla-4ac4c',
    authDomain: 'rahatla-4ac4c.firebaseapp.com',
    storageBucket: 'rahatla-4ac4c.firebasestorage.app',
    measurementId: 'G-PDN6CBTKQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWun1ZWsGQpqGyBFXNoEoEM96yKIPCKy8',
    appId: '1:661051223756:android:2af9bf2df5d1a56d825c69',
    messagingSenderId: '661051223756',
    projectId: 'rahatla-4ac4c',
    storageBucket: 'rahatla-4ac4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyIdNV2ph5EUcWQmCHItQTQ2CG78RRt5U',
    appId: '1:661051223756:ios:9c4e6aef73b5bc19825c69',
    messagingSenderId: '661051223756',
    projectId: 'rahatla-4ac4c',
    storageBucket: 'rahatla-4ac4c.firebasestorage.app',
    iosBundleId: 'com.rahatla.rahatlaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyIdNV2ph5EUcWQmCHItQTQ2CG78RRt5U',
    appId: '1:661051223756:ios:9c4e6aef73b5bc19825c69',
    messagingSenderId: '661051223756',
    projectId: 'rahatla-4ac4c',
    storageBucket: 'rahatla-4ac4c.firebasestorage.app',
    iosBundleId: 'com.rahatla.rahatlaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGqzRWmT4KxF0FcMPGhyIIYoZalfNym0U',
    appId: '1:661051223756:web:3d09a69c751f616c825c69',
    messagingSenderId: '661051223756',
    projectId: 'rahatla-4ac4c',
    authDomain: 'rahatla-4ac4c.firebaseapp.com',
    storageBucket: 'rahatla-4ac4c.firebasestorage.app',
    measurementId: 'G-C5LPX732LR',
  );
}
